### ISSUE TITLE
Rocky Linux 9 (RHEL9 likely too) selinux denial

### ISSUE THREAD

**Issue by agibson2** [pnp4nagios/pnp4nagios#35]
**Describe the bug**
When running pnp4nagios, selinux on Rocky Linux 9 is denying httpd access to the /var/lib/pnp4nagios/ directory.  The same result should be with Oracle Linux 9, AlmaLinux 9, RHEL 9, etc.

Not really a bug in pnp4nagios but an issue running it on Rocky Linux 9 where selinux is default enabled.  It needs a custom permission/module to allow selinux to access the directory.  I am hoping this might help others.  Feel free to close it and it can be here for future reference for others.

Versions:
pnp4nagios snapshot of master on 2022-09-29.
NagiosCore : nagios-4.4.14-1.el9.x86_64
apache: httpd-2.4.53-11.el9_2.5.x86_64
OS: Rocky Linux 9

**Additional context**
Error when viewing graph in pnp4nagios:
```
ERROR: mmaping file '/var/lig/pnp4nagios/servername/PING.rrd': Permission denied
```

These are the selinux errors you get...
```
type=PROCTITLE msg=audit(1696022291.553:129344): proctitle=2F7573722F62696E2F727264746F6F6C002D
type=SYSCALL msg=audit(1696022291.553:129344): arch=c000003e syscall=9 success=no exit=-13 a0=0 a1=bb8e0 a2=1 a3=4002 items=0 ppid=164519 pid=347790 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="rrdtool" exe="/usr/bin/rrdtool" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1696022291.553:129344): avc:  denied  { map } for  pid=347790 comm="rrdtool" path="/var/lib/pnp4nagios/servername/PING.rrd" dev="dm-0" ino=1048973 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:nagios_var_lib_t:s0 tclass=file permissive=0
```

Using ausearch, it suggests a custom module like this to allow it..

```
[root@server ~]# ausearch -c 'rrdtool' --raw | audit2allow -M my-httpd-pnp4nagios
******************** IMPORTANT ***********************
To make this policy package active, execute:

semodule -i my-httpd-pnp4nagios.pp

[root@server ~]# more my-httpd-pnp4nagios.
my-httpd-pnp4nagios.pp  my-httpd-pnp4nagios.te  
[root@server ~]# more my-httpd-pnp4nagios.te 

module my-httpd-pnp4nagios 1.0;

require {
	type nagios_var_lib_t;
	type httpd_t;
	class file map;
}

#============= httpd_t ==============

#!!!! This avc can be allowed using the boolean 'domain_can_mmap_files'
allow httpd_t nagios_var_lib_t:file map;
```

I did not want to allow the global domain_can_mmap_files as that would allow way more access than just allowing httpd to access it.

After creating that custom selinux module and inserting it, rrdtool under httpd can now access the /var/lib/pnp4nagios directory.

**Comment by agibson2** [comment]
To be clear, if someone sets the selinux boolean domain_can_mmap_files on RHEL 9 or derivatives, that will also work.  It will just be less restrictive.

```
setsebool domain_can_mmap_files 1
```

**Comment by celane** [comment]
Having just now finished up a big round of fixes, time
to come back to some slightly older issues. 

I tried selinux 4? 5? years ago, ran into so many security
complaints that I gave up and turned it off. I'm sure that a
lot of those problems were from having lots of packages that
were non-selinux-aware, so maybe it's better now.

For pnp4nagios, I think we could have a little subpackage,
something like "pnp4nagios-selinux-..." that contains the files
and setup for selinux; there's a "nagios-selinux" package that 
has that kind of thing, which can provide a guide.  

From your email, it looked like a ".te" file is needed. And a
.pp file? Couldn't tell for sure, but the nagios-selinux package
has 
Source13: nagios.README.SELinux.rst
Source14: nagios.te
Source15: nagios.fc
Source16: nagios.if

and then it runs make with /usr/share/selinux/devel/Makefile to get a
.pp file?  

I'm not sure if you want to pursue this further, it might be a lot
easier for pnp4nagios because we're just leeching from the nagios
setup, but let me know if you want to pursue this further.  


On Fri, 29 Sep 2023 14:36:56 -0700
agibson2 ***@***.***> wrote:

> **Describe the bug**
> When running pnp4nagios, selinux on Rocky Linux 9 is denying httpd
> access to the /var/lib/pnp4nagios/ directory.
> 
> Not really a bug in pnp4nagios but an issue running it on Rocky Linux
> 9 with selinux.  It needs a custom permission/module to allow selinux
> to access the directory.  I am hoping this might help others.
> 
> Versions:
> pnp4nagios snapshot of master on 2022-09-29.
> NagiosCore : nagios-4.4.14-1.el9.x86_64
> apache: httpd-2.4.53-11.el9_2.5.x86_64
> OS: Rocky Linux 9
> 
> **Additional context**
> These are the selinux errors you get...
> `type=PROCTITLE msg=audit(1696022291.553:129344):
> proctitle=2F7573722F62696E2F727264746F6F6C002D type=SYSCALL
> msg=audit(1696022291.553:129344): arch=c000003e syscall=9 success=no
> exit=-13 a0=0 a1=bb8e0 a2=1 a3=4002 items=0 ppid=164519 pid=347790
> auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48
> sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="rrdtool"
> exe="/usr/bin/rrdtool" subj=system_u:system_r:httpd_t:s0 key=(null)
> type=AVC msg=audit(1696022291.553:129344): avc:  denied  { map } for
> pid=347790 comm="rrdtool" path="/var/lib/pnp4nagios/how2/PING.rrd"
> dev="dm-0" ino=1048973 scontext=system_u:system_r:httpd_t:s0
> tcontext=system_u:object_r:nagios_var_lib_t:s0 tclass=file
> permissive=0`
> 
> Using ausearch, it suggests a custom module like this to allow it..
> `ausearch -c 'rrdtool' --raw | audit2allow -M my-httpd-pnp4nagios
> ******************** IMPORTANT ***********************
> To make this policy package active, execute:
> 
> semodule -i my-httpd-pnp4nagios.pp
> 
> ***@***.*** conf.d]# more my-httpd-pnp4nagios.
> my-httpd-pnp4nagios.pp  my-httpd-pnp4nagios.te  
> ***@***.*** conf.d]# more my-httpd-pnp4nagios.te 
> 
> module my-httpd-pnp4nagios 1.0;
> 
> require {
> 	type nagios_var_lib_t;
> 	type httpd_t;
> 	class file map;
> }
> 
> #============= httpd_t ==============
> 
> #!!!! This avc can be allowed using the boolean
> 'domain_can_mmap_files' allow httpd_t nagios_var_lib_t:file map;`
> 
> I did not want to allow the global domain_can_mmap_files as that
> would allow way more access than just allowing httpd to access it.
> 
> After creating that custom selinux module and inserting it, rrdtool
> under httpd can now access the /var/lib/pnp4nagios directory.
> 
> 



-- 
Drexel University  |/             /    ·   ν ·   Chuck Lane   |D
======]－－－>－－－C－－－－－π+－－<                Disque 911  |U
Particle Physics    \             \    ~~ e+~~   215-895-1545 |N
***@***.***                    －​μ+－－+νν                 |E
